### ISSUE TITLE
mac下运行失败

### ISSUE THREAD

**Issue by fenghaichun** [yueshutong/JavaMonitor#5]
01 Error attaching to process: sun.jvm.hotspot.debugger.DebuggerException: Can't attach symbolicator to the process
---->02 sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.debugger.DebuggerException: Can't attach symbolicator to the process
---->03 	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal$BsdDebuggerLocalWorkerThread.execute(BsdDebuggerLocal.java:169)
---->04 	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.attach(BsdDebuggerLocal.java:287)
---->05 	at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:671)
---->06 	at sun.jvm.hotspot.HotSpotAgent.setupDebuggerDarwin(HotSpotAgent.java:659)
---->07 	at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:341)
---->08 	at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
---->09 	at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
---->10 	at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
---->11 	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
---->12 	at sun.jvm.hotspot.tools.JInfo.main(JInfo.java:138)
---->13 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
---->14 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
---->15 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
---->16 	at java.lang.reflect.Method.invoke(Method.java:498)
---->17 	at sun.tools.jinfo.JInfo.runTool(JInfo.java:108)
---->18 	at sun.tools.jinfo.JInfo.main(JInfo.java:76)
---->19 Caused by: sun.jvm.hotspot.debugger.DebuggerException: Can't attach symbolicator to the process
---->20 	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.attach0(Native Method)
---->21 	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.access$100(BsdDebuggerLocal.java:65)
---->22 	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal$1AttachTask.doit(BsdDebuggerLocal.java:278)
---->23 	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal$BsdDebuggerLocalWorkerThread.run(BsdDebuggerLocal.java:144)

**Comment by yueshutong** [comment]
已了解，正在修复

**Comment by wangmingco** [comment]
请问这个问题怎么解决的?
